hooks:
  # hook scripts
  pre-commit:
    - golangci-lint run
    - husky lint-staged
    - go test -run '/^[^(example)].*/'

# list staged files do some pre-process and git add
lint-staged:
  "*.go":
    - goimports -l -w
    - gofmt -l -w
    - git add
